service: improve-v3
custom: 
  globallyUniquePrefix: ${self:service} # CHANGE THIS TO COMPANYNAME-PROJECTNAME-${self:service} # Unique prefix for s3 buckets, firehose stream names, and sagemaker endpoints
  firehoseS3ObjectCreatedSns: arn:aws:sns:us-west-2:117097735164:improve-v3-resources-${opt:stage, self:provider.stage}-FirehoseS3ObjectCreated
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  timeout: 6
  memorySize: 192
  environment:
    ALLOWED_MODELS: "messages-1.0,test-0.1" # Comma seperated list of allowed model names
    TRAINING_ROLE_ARN: FIX
    TRAINING_IMAGE: FIX
    TRAINING_INSTANCE_TYPE: ml.m5.large
    TRAINING_VOLUME_SIZE_IN_GB: 50
    TRAINING_MAX_RUNTIME_IN_SECONDS: 86400 # default 1 day
    HOSTING_INSTANCE_TYPE: ml.t2.medium
    HOSTING_INITIAL_INSTANCE_COUNT: 1 # set to the average number of hosting instances needed in production
    ENDPOINT_BASE_NAME: ${self:custom.globallyUniquePrefix}-${opt:stage, self:provider.stage}
    FIREHOSE_DELIVERY_STREAM_NAME: ${self:custom.globallyUniquePrefix}-resources-${opt:stage, self:provider.stage}-firehose
    RECORDS_BUCKET: ${self:custom.globallyUniquePrefix}-resources-${opt:stage, self:provider.stage}-records
    MODELS_BUCKET: ${self:custom.globallyUniquePrefix}-resources-${opt:stage, self:provider.stage}-models
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - "firehose:*"
      Resource: "arn:aws:firehose:*:*:deliverystream/${self:provider.environment.FIREHOSE_DELIVERY_STREAM_NAME}"
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: 'arn:aws:s3:::${self:custom.globallyUniquePrefix}-resources-${opt:stage, self:provider.stage}*'

functions:
  choose:
    handler: improve.choose
    events:
      - http:
          path: choose
          method: post
          cors: true
          private: true
  using:
    handler: improve.using
    events:
      - http:
          path: using
          method: post
          cors: true
          private: true
  rewards:
    handler: improve.rewards
    events:
      - http:
          path: rewards
          method: post
          cors: true
          private: true
  unpackFirehose:
    handler: improve.unpackFirehose
    timeout: 300
    events:
      - sns: ${self:custom.firehoseS3ObjectCreatedSns}
  dispatchParallelTrain:
    handler: improve.dispatchParallelTrain
    timeout: 300
    events:
      - schedule: rate(5 minutes)
  updateEndpoints:
    handler: improve.updateEndpointConfig
    timeout: 300
    events:
      - schedule: rate(1 minute)
