service: improve-v5-resources
provider:
  name: aws
  region: us-west-2
plugins:
  - serverless-pseudo-parameters
resources:
  Resources:
    FirehoseToS3Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${opt:stage, self:provider.stage}-FirehoseToS3Role
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - firehose.amazonaws.com
            Action:
            - sts:AssumeRole
        Policies:
        - PolicyName: FirehoseToS3Policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                - s3:AbortMultipartUpload
                - s3:GetBucketLocation
                - s3:GetObject
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:PutObject
                Resource: '*'
    SagemakerExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${opt:stage, self:provider.stage}-SagemakerExecutionRole
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - firehose.amazonaws.com
            Action:
            - sts:AssumeRole
          - Effect: Allow
            Principal:
              Service:
              - sagemaker.amazonaws.com
            Action:
            - sts:AssumeRole
        ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        Policies:
        - PolicyName: SagemakerExecutionPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                - s3:GetObject
                - s3:DeleteObject
                - s3:ListBucket
                - s3:PutObject
                Resource: "arn:aws:s3:::${self:service}-${opt:stage, self:provider.stage}-*-#{AWS::AccountId}*"
    FirehoseS3Bucket:
      Type: 'AWS::S3::Bucket'
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:service}-${opt:stage, self:provider.stage}-firehose-#{AWS::AccountId}
    V4Firehose:
      Type: AWS::KinesisFirehose::DeliveryStream
      Properties:
        DeliveryStreamName: ${self:service}-${opt:stage, self:provider.stage}-firehose
        S3DestinationConfiguration:
          BucketARN:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: FirehoseS3Bucket
          BufferingHints:
            IntervalInSeconds: "300"
            SizeInMBs: "128"
          CompressionFormat: "GZIP"
          RoleARN: { Fn::GetAtt: [ FirehoseToS3Role, Arn ] }
    RecordsS3Bucket:
      Type: 'AWS::S3::Bucket'
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:service}-${opt:stage, self:provider.stage}-records-#{AWS::AccountId}
    ModelsS3ObjectCreatedSnsTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        TopicName: ${self:service}-${opt:stage, self:provider.stage}-ModelsS3ObjectCreated
    ModelsS3ObjectCreatedSnsTopicPolicy:
      Type: 'AWS::SNS::TopicPolicy'
      Properties:
        Topics:
          - 
            Ref: ModelsS3ObjectCreatedSnsTopic
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 'sns:Publish'
              Resource:
                Ref: ModelsS3ObjectCreatedSnsTopic
              Principal:
                AWS: '*'
    ModelsS3Bucket:
      Type: 'AWS::S3::Bucket'
      DeletionPolicy: Retain
      DependsOn: ModelsS3ObjectCreatedSnsTopic
      Properties:
        BucketName: ${self:service}-${opt:stage, self:provider.stage}-models-#{AWS::AccountId}
        NotificationConfiguration:
          TopicConfigurations:
            - Topic:
                Ref: ModelsS3ObjectCreatedSnsTopic
              Event: 's3:ObjectCreated:*'
    PublicModelsS3Bucket:
      Type: 'AWS::S3::Bucket'
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:service}-${opt:stage, self:provider.stage}-public-models-#{AWS::AccountId}

  Outputs:
    V4Firehose:
      Value:
        Ref: V4Firehose
    FirehoseS3Bucket:
      Value: 
        Ref: FirehoseS3Bucket
    RecordsS3Bucket:
      Value: 
        Ref: RecordsS3Bucket
    ModelsS3Bucket:
      Value: 
        Ref: ModelsS3Bucket
    PublicModelsS3Bucket:
      Value: 
        Ref: PublicModelsS3Bucket
    ModelsS3ObjectCreatedSnsTopic:
      Value: 
        Ref: ModelsS3ObjectCreatedSnsTopic
    SagemakerExecutionRoleArn:
      Value: { Fn::GetAtt: [ SagemakerExecutionRole, Arn ] } 