---
#
# deployment level configuration. The names of provisioned AWS resources depend on these values
#
region: us-east-1
organization: acme # CHANGE ME BEFORE FIRST DEPLOYMENT
project: demo # CHANGE ME BEFORE FIRST DEPLOYMENT

contact: example@example.com # CHANGE ME BEFORE FIRST DEPLOYMENT

#
# Subscribe to the Improve AI decision model trainer, add image URL here
#
# SUBSCRIBE HERE: XXX
#
training_image: https://docker.example.com/decision_trainer:latest # CHANGE ME BEFORE FIRST DEPLOYMENT

#
# decision models to train
#
# 'appconfig' is the default decision model used by the AIAppConfig classes, remove if not using AIAppConfig
#
models:
  appconfig: 

defaults:
  max_record_age_in_seconds: 15552000 # 180 days
  training:
    schedule: rate(24 hours)
    worker_instance_type: ml.m5.large
    worker_count: 3 
    max_records_per_worker: 500000 # limited by worker memory
    max_runtime_in_seconds: 172800 # 48 hours
  reward_assignment:
    schedule: rate(4 hours)
    worker_count: 10
    spot_bid_percentage: 100
    reward_window_in_seconds: 172800 # 48 hours
