---
#
# deployment level configuration. The names of provisioned AWS resources depend
# on these values. 
#
# 'organization' and 'project' may contain only lowercase letters and numbers
#
region: us-east-1
organization: acme # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
project: demo # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
contact: your_email@example.com # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!

#
# decision models to train
#
# 'appconfig' is the default decision model used by the "Improve" helper class
#
models:
  appconfig:


training:
  # get your training image URL by subscribing to the decision model trainer at 
  # XXX
  image: XXX.dkr.ecr.us-east-1.amazonaws.com/improveai-trainer:latest # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
  schedule: rate(24 hours)
  worker_instance_type: ml.m5.large
  worker_count: 2
  max_runtime: 4 hours # 4 hours
  volume_size_in_gb: 10
