---
#
# The names of provisioned AWS resources depend on 'organization' and 'project'. AWS resource
# names generally follow the pattern 'improveai-<organization>-<project>-<stage>-<resource>'
#
# 'organization' and 'project' may contain only lowercase letters and numbers
#
organization: acme # ⬅️ !!! CHANGE BEFORE FIRST DEPLOYMENT !!!
project: demo # ⬅️ !!! CHANGE BEFORE FIRST DEPLOYMENT !!!
contact: your_email@example.com # ⬅️ !!! CHANGE BEFORE FIRST DEPLOYMENT !!!

aws_region: us-east-1


#
# decision models to train
#
models:
#  config: # uncomment to train a model named 'config'

# Default training configuration
training:
  # get your training image URL by subscribing to the Improve AI Trainer at 
  # XXX
  image: XXX.dkr.ecr.us-east-1.amazonaws.com/improveai-trainer:latest # ⬅️ !!! CHANGE BEFORE FIRST DEPLOYMENT !!!
  schedule: rate(15 minutes)
  instance_type: ml.m5.xlarge
  instance_count: 2
  max_runtime: 4 hours # AWS instances sometimes hang. This caps training costs when that occurs.
  volume_size: 10 GB
  hyperparameters:
    max_decision_records: 20000000 # Note: the free trainer is capped at 100,000 decision records per model
