---
organization: acme # CHANGE ME BEFORE FIRST DEPLOYMENT
project: demo # CHANGE ME BEFORE FIRST DEPLOYMENT

models:
  # changeme: Plural nouns of the variant type are recommended for model names, such as "themes", "prices", or "songs"
  appconfig:
    size: xsmall # sizes? 
  messages-2.0:
    size: medium
  themes-2.0:
    size: medium
  songs-2.0:
    size: medium
  stories-2.0:
    size: medium

defaults:
  max_record_age_in_seconds: 15552000 # 180 days
  region: us-east-1
  training:
    # INFO: ECR image repo region must match region set in here
    image: 117097735164.dkr.ecr.us-west-2.amazonaws.com/improve_trainer-dev:latest
    schedule: rate(24 hours)
    worker_instance_type: ml.m5.large # instance_type ? 
    worker_count: 3 
    max_runtime_in_seconds: 172800 # 48 hours
    max_records_per_worker: 500000 
  reward_assignment:
    worker_count: 10
    spot_bid_percentage: 100
    schedule: rate(4 hours)
    reward_window_in_seconds: 172800 # 48 hours
