---
#
# deployment level configuration. The names of provisioned AWS resources depend
# on these values. 
#
# 'organization' and 'project' may contain only lowercase letters and numbers
#
region: us-east-1
organization: acme # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
project: demo # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
contact: your_email@example.com # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!

#
# decision models to train
#
# 'appconfig' is the default decision model used by the "Improve" helper class
#
models:
  appconfig: 

training:
  # get your training image URL by subscribing to the decision model trainer at 
  # XXX
  image: XXX.dkr.ecr.us-east-1.amazonaws.com/improveai-trainer:latest # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
  schedule: rate(6 hours)
  worker_instance_type: ml.m5.xlarge
  worker_count: 2
  max_runtime_in_seconds: 7200 # 2 hours

reward_assignment:
  schedule: rate(4 hours)
  worker_count: 8
  spot_bid_percentage: 100
  reward_window_in_seconds: 172800 # 48 hours
  default_event_value: 0.001 # the reward value for any event without a 'value' property occuring within the reward window
  retention_bonus: 0.01 # one time bonus per decision for any tracked activity after the reward window
  
deployment:
  metadata:
    Cache-Control: max-age=172800,s-maxage=900 # 48 hours for client caches, 15 minutes for CDNs
