---
#
# deployment level configuration. The names of provisioned AWS resources depend
# on these values. 
#
# 'organization' and 'project' may contain only lowercase letters and numbers
#
region: us-east-1
organization: acme # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
project: demo # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
contact: example@example.com # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!

#
# decision models to train
#
# 'appconfig' is the default decision model used by the AIAppConfig classes
#
models:
  appconfig: 

training:
  # get a training image URL by subscribing to the decision model trainer at 
  # XXX
  image: https://docker.example.com/decision_trainer:latest # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
  schedule: rate(24 hours)
  worker_instance_type: ml.m5.large
  worker_count: 3 
  max_records_per_worker: 500000 # limited by worker instance memory
  max_runtime_in_seconds: 172800 # 48 hours

reward_assignment:
  schedule: rate(4 hours)
  worker_count: 10
  spot_bid_percentage: 100
  reward_window_in_seconds: 172800 # 48 hours