---
#
# deployment level configuration. The names of provisioned AWS resources depend
# on these values. 
#
# 'organization' and 'project' may contain only lowercase letters and numbers
#
region: us-east-2
organization: acme # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
project: demo # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
contact: your_email@example.com # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!

#
# decision models to train
#
# 'appconfig' is the default decision model used by the "Improve" helper class
#
models:
  appconfig: 

training:
  # get your training image URL by subscribing to the decision model trainer at 
  # XXX
  image: 278455137857.dkr.ecr.us-east-2.amazonaws.com/improve.ai:v6_trainer # !!! CHANGE ME BEFORE FIRST DEPLOYMENT !!!
  schedule: rate(168 hours)
  worker_instance_type: ml.m5.large
  worker_count: 1
  max_runtime_in_seconds: 7200 # 2 hours