---
organization: acme # CHANGE ME BEFORE FIRST DEPLOYMENT
project: demo # CHANGE ME BEFORE FIRST DEPLOYMENT

rewardWindowInSeconds: 172800
maxAge: 7776000
xgboostHyperparameters:
  num_round: "300"
  early_stopping_rounds: "40"
  objective: "binary:logistic"
  eval_metric: "auc"
  max_depth: "6" 
  eta: "0.1"
  subsample: "0.7"
  colsample_bytree: "0.7"

projects:
  test:
    models:
      default_model:
  bible:
    models:
      messages-2.0:
      themes-2.0:
        xgboostHyperparameters:
          max_depth: 4
          num_round: 150
      songs-2.0:
      stories-2.0:
  mindful:
    models:
      messages-2.0:
      themes-2.0:
        xgboostHyperparameters:
          max_depth: 4
          num_round: 150.0
      songs-2.0:
      stories-2.0:
